//Calendar
  const date = new Date();
  const Days = ['niedziela', 'poniedziałek', 'wtorek', 'środa', 'czwartek', 'piątek', 'sobota'];
  const Weekday = Days[new Date().getDay()];
  const Day = new Date().getUTCDate();
  const Year = new Date().getUTCFullYear();
  const MonthLong = date.toLocaleString('pl-pl', { month: 'long' });
  const currentDate = new Intl.DateTimeFormat('en-US', { month: '2-digit', day: '2-digit' }).format(
    date,
  );

document.getElementById('date').innerHTML =  Weekday+" "+Day+" "+MonthLong+" "+Year+"r.";


//Name day

const names = [
  { day: "01/01", nameDay: "Mieszka, Mieczysława, Marii" },
  { day: "01/02", nameDay: "Izydora, Bazylego, Grzegorza" },
  { day: "01/03", nameDay: "Arlety, Genowefy, Danuty" },
  { day: "01/04", nameDay: "Tytusa, Anieli, Eugeniusza" },
  { day: "01/05", nameDay: "Hanny, Szymona, Edwarda" },
  { day: "01/06", nameDay: "Kacpra, Melchiora, Baltazara" },
  { day: "01/07", nameDay: "Seweryna, Mścisława, Juliusza" },
  { day: "01/08", nameDay: "Seweryna, Mścisława, Juliusza" },
  { day: "01/09", nameDay: "Marceliny, Marianny, Juliana" },
  { day: "01/10", nameDay: "Wilhelma, Dobrosława, Danuty" },
  { day: "01/11", nameDay: "Honoraty, Teodozjusza, Matyldy" },
  { day: "01/12", nameDay: "Grety, Arkadiusza, Rajmunda" },
  { day: "01/13", nameDay: "Bogumiły, Weroniki, Hilarego" },
  { day: "01/14", nameDay: "Feliksa, Domosława, Niny" },
  { day: "01/15", nameDay: "Pawła, Arnolda, Izydora" },
  { day: "01/16", nameDay: "Marcelego, Włodzimierza, Waldemara" },
  { day: "01/17", nameDay: "Antoniego, Rościsława, Jana" },
  { day: "01/18", nameDay: "Piotra, Małgorzaty" },
  { day: "01/19", nameDay: "Henryka, Mariusza, Marty" },
  { day: "01/20", nameDay: "Fabiana, Sebastiana" },
  { day: "01/21", nameDay: "Agnieszki, Jarosława" },
  { day: "01/22", nameDay: "Anastazego, Wincenteg" },
  { day: "01/23", nameDay: "Ildefonsa, Rajmunda" },
  { day: "01/24", nameDay: "Felicji, Franciszka, Rafała" },
  { day: "01/25", nameDay: "Pawła, Miłosza, Elwiry" },
  { day: "01/26", nameDay: "Tymoteusza, Michała, Tytusa" },
  { day: "01/27", nameDay: "Przybysława, Anieli, Jerzego" },
  { day: "01/28", nameDay: "Walerego, Radomira, Tomasza" },
  { day: "01/29", nameDay: "Zdzisława, Franciszka, Józefa" },
  { day: "01/30", nameDay: "Macieja, Martyny, Teofila" },
  { day: "01/31", nameDay: "Marceli, Ludwiki, Jana" },
  { day: "02/01", nameDay: "Brygidy, Ignacego, Seweryna" },
  { day: "02/02", nameDay: "Marii, Miloslawa" },
  { day: "02/03", nameDay: "Blazeja, Oskara" },
  { day: "02/04", nameDay: "Andrzeja, Weroniki, Joanny" },
  { day: "02/05", nameDay: "Agaty, Adelajdy" },
  { day: "02/06", nameDay: "Doroty, Bogdana, Pawła" },
  { day: "02/07", nameDay: "Ryszarda, Teodora, Romana" },
  { day: "02/08", nameDay: "Hieronima, Sebastiana, Ireny" },
  { day: "02/09", nameDay: "Apolonii, Eryki, Cyryla" },
  { day: "02/10", nameDay: "Elwiry, Jacka, Scholastyki" },
  { day: "02/11", nameDay: "Lucjana, Olgierda" },
  { day: "02/12", nameDay: "Eulalii, Radoslawa, Modesta" },
  { day: "02/13", nameDay: "Grzegorza, Katarzyny" },
  { day: "02/14", nameDay: "Cyryla, Metodego, Walentego" },
  { day: "02/15", nameDay: "Jowity, Faustyna, Zygfryda" },
  { day: "02/16", nameDay: "Danuty, Julianny, Daniela" },
  { day: "02/17", nameDay: "Aleksego, Zbigniewa, Lukasza" },
  { day: "02/18", nameDay: "Szymona, Konstancji, Flawiana" },
  { day: "02/19", nameDay: "Arnolda, Konrada, Marcelego" },
  { day: "02/20", nameDay: "Leona, Ludomira, Zenobiusza" },
  { day: "02/21", nameDay: "Eleonory, Fortunata, Roberta" },
  { day: "02/22", nameDay: "Marty, Malgorzaty, Piotra" },
  { day: "02/23", nameDay: "Romany, Damiana, Polikarpa" },
  { day: "02/24", nameDay: "Macieja, Bogusza, Sergiusza" },
  { day: "02/25", nameDay: "Wiktora, Cezarego" },
  { day: "02/26", nameDay: "Miroslawa, Aleksandra" },
  { day: "02/27", nameDay: "Gabriela, Anastazji" },
  { day: "02/28", nameDay: "Romana, Ludomira, Lecha" },
  { day: "02/29", nameDay: "Lecha, Lutoslawa" },
  { day: "03/01", nameDay: "Antoniny, Radoslawa, Dawida" },
  { day: "03/02", nameDay: "Heleny, Halszki, Pawła" },
  { day: "03/03", nameDay: "Maryny, Kunegundy, Tycjana" },
  { day: "03/04", nameDay: "Lucji, Kazimierza, Eugeniusza" },
  { day: "03/05", nameDay: "Adriana, Fryderyka, Teofila" },
  { day: "03/06", nameDay: "Rózy, Jordana, Agnieszki" },
  { day: "03/07", nameDay: "Tomasza, Perpetuy, Felicyty" },
  { day: "03/08", nameDay: "Beaty, Wincentego, Jana" },
  { day: "03/09", nameDay: "Franciszki, Brunona" },
  { day: "03/10", nameDay: "Cypriana, Marcela, Aleksandra" },
  { day: "03/11", nameDay: "Ludoslawa, Konstantyna, Benedykta" },
  { day: "03/12", nameDay: "Grzegorza, Justyna, Alojzego" },
  { day: "03/13", nameDay: "Bozeny, Krystyny" },
  { day: "03/14", nameDay: "Leona, Matyldy, Lazarza" },
  { day: "03/16", nameDay: "Longina, Klemensa, Ludwiki" },
  { day: "03/16", nameDay: "Izabeli, Oktawii, Hilarego" },
  { day: "03/17", nameDay: "Patryka, Zbigniewa, Gertrudy" },
  { day: "03/18", nameDay: "Cyryla, Edwarda, Boguchwaly" },
  { day: "03/19", nameDay: "Józefa, Bogdana" },
  { day: "03/20", nameDay: "Klaudii, Eufemii, Maurycego" },
  { day: "03/21", nameDay: "Lubomira, Benedykta" },
  { day: "03/22", nameDay: "Katarzyny, Boguslawa" },
  { day: "03/23", nameDay: "Pelagii, Oktawiana, Feliksa" },
  { day: "03/24", nameDay: "Marka, Gabriela, Katarzyny" },
  { day: "03/25", nameDay: "Marioli, Wieczyslawa, Ireneusza" },
  { day: "03/26", nameDay: "Larysy, Emanyela, Teodora" },
  { day: "03/27", nameDay: "Lidii, Ernesta" },
  { day: "03/28", nameDay: "Anieli, Sykstusa, Jana" },
  { day: "03/29", nameDay: "Wiktoryna, Helmuta, Eustachego" },
  { day: "03/30", nameDay: "Anieli, Kwiryna, Leonarda" },
  { day: "03/31", nameDay: "Beniamina, Dobromierza, Leonarda" },
  { day: "04/01", nameDay: "Teodory, Grazyny, Ireny" },
  { day: "04/02", nameDay: "Wladyslawa, Franciszka, Teodozji" },
  { day: "04/03", nameDay: "Ryszarda, Pankracego, Ingi" },
  { day: "04/04", nameDay: "Izydora, Waclawa" },
  { day: "04/05", nameDay: "Ireny, Wincentego" },
  { day: "04/06", nameDay: "Izoldy, Celestyna, Wilhelma" },
  { day: "04/07", nameDay: "Rufina, Celestyna, Jana" },
  { day: "04/08", nameDay: "Cezaryny, Dionizego, Julii" },
  { day: "04/09", nameDay: "Marii, Dymitra, Heliodora" },
  { day: "04/10", nameDay: "Michala, Makarego" },
  { day: "04/11", nameDay: "Filipa, Leona" },
  { day: "04/12", nameDay: "Juliusza, Luboslawa, Zenona" },
  { day: "04/13", nameDay: "Przemyslawa, Hermenegildy, Marcina" },
  { day: "04/14", nameDay: "Bereniki, Waleriana, Justyny" },
  { day: "04/15", nameDay: "Ludwiny, Waclawy, Anastazji" },
  { day: "04/16", nameDay: "Kseni, Cecylii, Bernardety" },
  { day: "04/17", nameDay: "Rudolfa, Roberta" },
  { day: "04/18", nameDay: "Boguslawy, Apoloniusza" },
  { day: "04/19", nameDay: "Adolfa, Tymona, Leona" },
  { day: "04/20", nameDay: "Czeslawa, Agnieszki, Mariana" },
  { day: "04/21", nameDay: "Anzelma, Bartosza, Feliksa" },
  { day: "04/22", nameDay: "Kai, Leonii, Sotera" },
  { day: "04/23", nameDay: "Jerzego, Wojciecha" },
  { day: "04/24", nameDay: "Horacego, Feliksa, Grzegorza" },
  { day: "04/25", nameDay: "Marka, Jaroslawa, Wasyla" },
  { day: "04/26", nameDay: "Marzeny, Klaudiusza, Marii" },
  { day: "04/27", nameDay: "Zyty, Teofila, Felicji" },
  { day: "04/28", nameDay: "Piotra, Walerii, Witalisa" },
  { day: "04/29", nameDay: "Rity, Katarzyny, Boguslawa" },
  { day: "04/30", nameDay: "Mariana, Donaty, Tamary" },
  { day: "05/01", nameDay: "Józefa, Jeremiasza, Filipa" },
  { day: "05/02", nameDay: "Zygmunta, Atanazego, Anatola" },
  { day: "05/03", nameDay: "Marii, Antoniny" },
  { day: "05/04", nameDay: "Moniki, Floriana, Wladyslawa" },
  { day: "05/05", nameDay: "Ireny, Waldemara" },
  { day: "05/06", nameDay: "Judyty, Jakuba, Filipa" },
  { day: "05/07", nameDay: "Gizeli, Ludmily, Benedykta" },
  { day: "05/08", nameDay: "Stanislawa, Lizy, Wiktora" },
  { day: "05/09", nameDay: "Bozydara, Grzegorza, Karoliny" },
  { day: "05/10", nameDay: "Izydora, Antoniny, Symeona" },
  { day: "05/11", nameDay: "Igi, Miry, Wladyslawy" },
  { day: "05/12", nameDay: "Pankracego, Dominika, Achillesa" },
  { day: "05/13", nameDay: "Serwacego, Roberta, Glorii" },
  { day: "05/14", nameDay: "Bonifacego, Dobieslawa, Macieja" },
  { day: "05/15", nameDay: "Zofii, Nadziei, Izydora" },
  { day: "05/16", nameDay: "Andrzeja, Jedrzeja, Szymona" },
  { day: "05/17", nameDay: "Paschalisa, Slawomira, Weroniki" },
  { day: "05/18", nameDay: "Eryka, Feliksa, Jana" },
  { day: "05/19", nameDay: "Iwa, Piotra, Celestyna" },
  { day: "05/20", nameDay: "Bazylego, Bernardyna, Aleksandra" },
  { day: "05/21", nameDay: "Wiktora, Kryspina, Tymoteusza" },
  { day: "05/22", nameDay: "Heleny, Wieslawy, Ryty" },
  { day: "05/23", nameDay: "Iwony, Dezyderego, Kryspina" },
  { day: "05/24", nameDay: "Joanny, Zuzanny" },
  { day: "05/25", nameDay: "Grzegorza, Urbana, Magdaleny" },
  { day: "05/26", nameDay: "Filipa, Pauliny" },
  { day: "05/27", nameDay: "Augustyna, Juliana, Magdaleny" },
  { day: "05/28", nameDay: "Jaromira, Justa, Justyny" },
  { day: "05/29", nameDay: "Magdaleny, Bogumily, Urszuli" },
  { day: "05/30", nameDay: "Ferdynanda, Karola, Jana" },
  { day: "05/31", nameDay: "Anieli, Petroneli" },
  { day: "06/01", nameDay: "Justyna, Anieli, Konrada" },
  { day: "06/02", nameDay: "Marianny, Marcelina, Piotra" },
  { day: "06/03", nameDay: "Leszka, Tamary, Karola" },
  { day: "06/04", nameDay: "Kwiryny, Franciszka" },
  { day: "06/05", nameDay: "Waltera, Bonifacego, Walerii" },
  { day: "06/06", nameDay: "Norberta, Laurentego, Bogumila" },
  { day: "06/07", nameDay: "Roberta, Wieslawa" },
  { day: "06/08", nameDay: "Medarda, Maksyma, Seweryna" },
  { day: "06/09", nameDay: "Pelagii, Dominika, Efrema" },
  { day: "06/10", nameDay: "Bogumila, Malgorzaty, Diany" },
  { day: "06/11", nameDay: "Barnaby, Radomila, Feliksa" },
  { day: "06/12", nameDay: "Janiny, Onufrego, Leona" },
  { day: "06/13", nameDay: "Lucjana, Antoniego" },
  { day: "06/14", nameDay: "Bazylego, Elwiry, Michala" },
  { day: "06/15", nameDay: "Wita, Jolanty" },
  { day: "06/16", nameDay: "Aliny, Benona, Anety" },
  { day: "06/17", nameDay: "Laury, Marcjana, Alberta" },
  { day: "06/18", nameDay: "Marka, Elzbiety" },
  { day: "06/19", nameDay: "Gerwazego, Protazego" },
  { day: "06/20", nameDay: "Diny, Bogny, Florentyny" },
  { day: "06/21", nameDay: "Alicji, Alojzego" },
  { day: "06/22", nameDay: "Pauliny, Tomasza, Jana" },
  { day: "06/23", nameDay: "Wandy, Zenona" },
  { day: "06/24", nameDay: "Jana, Danuty" },
  { day: "06/25", nameDay: "Lucji, Wilhelma, Doroty" },
  { day: "06/26", nameDay: "Jana, Pawla" },
  { day: "06/27", nameDay: "Maryli, Wladyslawa, Cyryla" },
  { day: "06/28", nameDay: "Leona, Ireneusza" },
  { day: "06/29", nameDay: "Piotra, Pawla" },
  { day: "06/30", nameDay: "Emilii, Lucyny" },
  { day: "07/01", nameDay: "Haliny, Mariana, Marcina" },
  { day: "07/02", nameDay: "Jagody, Urbana, Marii" },
  { day: "07/03", nameDay: "Jacka, Anatola, Tomasza" },
  { day: "07/04", nameDay: "Odona, Malwiny, Elzbiety" },
  { day: "07/05", nameDay: "Marii, Antoniego" },
  { day: "07/06", nameDay: "Gotarda, Dominiki, Lucji" },
  { day: "07/07", nameDay: "Cyryla, Estery, Metodego" },
  { day: "07/08", nameDay: "Edgara, Elzbiety, Eugeniusza" },
  { day: "07/09", nameDay: "Lukrecji, Weroniki, Zenona" },
  { day: "07/10", nameDay: "Sylwany, Witalisa, Antoniego" },
  { day: "07/11", nameDay: "Olgi, Kaliny, Benedykta" },
  { day: "07/12", nameDay: "Jana, Brunona, Bonifacego" },
  { day: "07/13", nameDay: "Henryka, Kingi, Andrzeja" },
  { day: "07/14", nameDay: "Ulryka, Bonawentury, Kamila" },
  { day: "07/15", nameDay: "Henryka, Wlodzimierza, Dawida" },
  { day: "07/16", nameDay: "Mariki, Benity, Eustachego" },
  { day: "07/17", nameDay: "Anety, Bogdana, Jadwigi" },
  { day: "07/18", nameDay: "Erwina, Kamila, Szymona" },
  { day: "07/19", nameDay: "Wincentego, Wodzislawa, Marcina" },
  { day: "07/20", nameDay: "Czeslawa, Hieronima, Malgorzaty" },
  { day: "07/21", nameDay: "Daniela, Diany, Wawrzynca" },
  { day: "07/22", nameDay: "Marii, Magdaleny" },
  { day: "07/23", nameDay: "Stwosza, Bogny, Brygidy" },
  { day: "07/24", nameDay: "Kingi, Krystyny" },
  { day: "07/25", nameDay: "Walentyny, Krzysztofa, Jakuba" },
  { day: "07/26", nameDay: "Anny, Miroslawy, Grazyny" },
  { day: "07/27", nameDay: "Lilii, Julii, Natalii" },
  { day: "07/28", nameDay: "Aidy, Marceli, Wiktora" },
  { day: "07/29", nameDay: "Olafa, Marty, Ludmily" },
  { day: "07/30", nameDay: "Julity, Piotra, Aldony" },
  { day: "07/31", nameDay: "Ignacego, Lubomira, Heleny" },
  { day: "08/01", nameDay: "Nadii, Justyna, Juliana" },
  { day: "08/02", nameDay: "Kariny, Gustawa, Euzebiusza" },
  { day: "08/03", nameDay: "Lidii, Augusta, Nikodema" },
  { day: "08/04", nameDay: "Dominika, Protazego, Jana" },
  { day: "08/05", nameDay: "Oswalda, Marii, Mariana" },
  { day: "08/06", nameDay: "Slawy, Jakuba, Oktawiana" },
  { day: "08/07", nameDay: "Kajetana, Doroty, Sykstusa" },
  { day: "08/08", nameDay: "Cypriana, Emiliana, Dominika" },
  { day: "08/09", nameDay: "Romana, Ryszarda, Edyty" },
  { day: "08/10", nameDay: "Borysa, Filomeny, Wawrzynca" },
  { day: "08/11", nameDay: "Klary, Zuzanny, Lecha" },
  { day: "08/12", nameDay: "Innocentego, Lecha, Euzebii" },
  { day: "08/13", nameDay: "Diany, Hipolita, Poncjana" },
  { day: "08/14", nameDay: "Alfreda, Euzebiusza, Maksymiliana" },
  { day: "08/15", nameDay: "Napoleona, Stelii" },
  { day: "08/16", nameDay: "Rocha, Stefana, Joachima" },
  { day: "08/17", nameDay: "Zanny, Mirona, Jacka" },
  { day: "08/18", nameDay: "Ilony, Bronislawa, Heleny" },
  { day: "08/19", nameDay: "Boleslawa, Juliana" },
  { day: "08/20", nameDay: "Bernarda, Samuela, Sobieslawa" },
  { day: "08/21", nameDay: "Joanny, Kazimiery, Piusa" },
  { day: "08/22", nameDay: "Cezarego, Tymoteusza" },
  { day: "08/23", nameDay: "Apolinarego, Filipa" },
  { day: "08/24", nameDay: "Jerzego, Bartosza, Haliny" },
  { day: "08/25", nameDay: "Luizy, Ludwika, Józefa" },
  { day: "08/26", nameDay: "Marii, Aleksandra" },
  { day: "08/27", nameDay: "Cezarego, Józefa, Moniki" },
  { day: "08/28", nameDay: "Patrycji, Wyszomira, Augustyna" },
  { day: "08/29", nameDay: "Beaty, Jana, Sabiny, Racibora" },
  { day: "08/30", nameDay: "Rózy, Szczesnego, Feliksa" },
  { day: "08/31", nameDay: "Bogdana, Ramony, Rajmunda" },
  { day: "09/01", nameDay: "Idziego, Bronislawa" },
  { day: "09/02", nameDay: "Juliana, Stefana, Wilhelma" },
  { day: "09/03", nameDay: "Grzegorza, Izabeli, Szymona" },
  { day: "09/04", nameDay: "Idy, Julianny, Rozalii, Rózy" },
  { day: "09/05", nameDay: "Doroty, Teodora, Wawrzynca" },
  { day: "09/06", nameDay: "Beaty, Eugeniusza" },
  { day: "09/07", nameDay: "Domoslawy, Melchiora, Reginy" },
  { day: "09/08", nameDay: "Marii, Adrianny, Serafiny" },
  { day: "09/09", nameDay: "¦cibora, Sergiusza, Piotra" },
  { day: "09/10", nameDay: "Lukasza, Aldony, M?cislawa" },
  { day: "09/11", nameDay: "Jacka, Prota, Dagny, Hiacynta" },
  { day: "09/12", nameDay: "Gwidona, Radzimira, Marii" },
  { day: "09/13", nameDay: "Eugenii, Aureliusza, Jana" },
  { day: "09/14", nameDay: "Roksany, Bernarda, Cypriana" },
  { day: "09/15", nameDay: "Albina, Nikodema, Marii" },
  { day: "09/16", nameDay: "Edyty, Korneliusza, Cypriana" },
  { day: "09/17", nameDay: "Franciszka, Roberta, Justyna" },
  { day: "09/18", nameDay: "Irmy, Stanislawa, Ireny" },
  { day: "09/19", nameDay: "Januarego, Konstancji, Teodora" },
  { day: "09/20", nameDay: "Filipiny, Eustachego, Euzebii" },
  { day: "09/21", nameDay: "Jonasza, Mateusza, Hipolita" },
  { day: "09/22", nameDay: "Tomasza, Maurycego, Joachima" },
  { day: "09/23", nameDay: "Tekli, Boguslawa, Linusa" },
  { day: "09/24", nameDay: "Gerarda, Ruperta, Tomiry" },
  { day: "09/25", nameDay: "Aurelii, Wladyslawa, Kleofasa" },
  { day: "09/26", nameDay: "Wawrzynca, Kosmy, Damiana" },
  { day: "09/27", nameDay: "Wincentego, Mirabeli, Justyny" },
  { day: "09/28", nameDay: "Waclawa, Tymona, Marka" },
  { day: "09/29", nameDay: "Michala, Gabriela, Rafala" },
  { day: "09/30", nameDay: "Wery, Honoriusza, Hieronima" },
  { day: "10/01", nameDay: "Danuty, Remigiusza, Teresy" },
  { day: "10/02", nameDay: "Teofila, Dionizego, Slawomira" },
  { day: "10/03", nameDay: "Teresy, Heliodora, Jana" },
  { day: "10/04", nameDay: "Rozalii, Edwina, Franciszka" },
  { day: "10/05", nameDay: "Placyda, Apolinarego" },
  { day: "10/06", nameDay: "Artura, Brunona" },
  { day: "10/07", nameDay: "Marii, Marka, Mirelli" },
  { day: "10/08", nameDay: "Pelagii, Brygidy, Walerii" },
  { day: "10/09", nameDay: "Amolda, Dionizego, Wincentego" },
  { day: "10/10", nameDay: "Pauliny, Danieli, Leona" },
  { day: "10/11", nameDay: "Aldony, Aleksandra, Dobromiry" },
  { day: "10/12", nameDay: "Eustachego, Maksymiliana, Edwina" },
  { day: "10/13", nameDay: "Geralda, Edwarda, Honorata" },
  { day: "10/14", nameDay: "Liwii, Kaliksta, Bernarda" },
  { day: "10/15", nameDay: "Jadwigi, Teresy, Florentyny" },
  { day: "10/16", nameDay: "Gawla, Ambrozego" },
  { day: "10/17", nameDay: "Wiktora, Marity, Ignacego" },
  { day: "10/18", nameDay: "Juliana, Lukasza" },
  { day: "10/19", nameDay: "Ziemowita, Jana, Pawla" },
  { day: "10/20", nameDay: "Ireny, Kleopatry, Jana" },
  { day: "10/21", nameDay: "Urszuli, Hilarego, Jakuba" },
  { day: "10/22", nameDay: "Halki, Filipa, Salomei" },
  { day: "10/23", nameDay: "Marleny, Seweryna, Igi" },
  { day: "10/24", nameDay: "Rafala, Marcina, Antoniego" },
  { day: "10/25", nameDay: "Darii, Wilhelminy, Bonifacego" },
  { day: "10/26", nameDay: "Lucjana, Ewarysta, Damiana" },
  { day: "10/27", nameDay: "Iwony, Sabiny" },
  { day: "10/28", nameDay: "Szymona, Tadeusza" },
  { day: "10/29", nameDay: "Euzebii, Wioletty, Felicjana" },
  { day: "10/30", nameDay: "Zenobii, Przemyslawa, Edmunda" },
  { day: "10/31", nameDay: "Urbana, Saturnina, Krzysztofa" },
  { day: "11/01", nameDay: "Seweryna, Wiktoryny" },
  { day: "11/02", nameDay: "Bohdany, Bozydara" },
  { day: "11/03", nameDay: "Sylwii, Marcina, Huberta" },
  { day: "11/04", nameDay: "Karola, Olgierda" },
  { day: "11/05", nameDay: "Elzbiety, Slawomira, Dominika" },
  { day: "11/06", nameDay: "Feliksa, Leonarda, Ziemowita" },
  { day: "11/07", nameDay: "Antoniego, Zytomira, Ernesta" },
  { day: "11/08", nameDay: "Seweryna, Bogdana, Klaudiusza" },
  { day: "11/09", nameDay: "Aleksandra, Ludwika, Teodora" },
  { day: "11/10", nameDay: "Leny, Ludomira, Leona" },
  { day: "11/11", nameDay: "Marcina, Batlomieja, Teodora" },
  { day: "11/12", nameDay: "Renaty, Witolda, Jozafata" },
  { day: "11/13", nameDay: "Mateusza, Izaaka, Stanislawa" },
  { day: "11/14", nameDay: "Rogera, Serafina, Wawrzynca" },
  { day: "11/15", nameDay: "Alberta, Leopolda" },
  { day: "11/16", nameDay: "Gertrudy, Edmunda, Marii" },
  { day: "11/17", nameDay: "Salomei, Grzegorza, Elzbiety" },
  { day: "11/18", nameDay: "Romana, Klaudyny, Karoliny" },
  { day: "11/19", nameDay: "Seweryny, Maksyma, Salomei" },
  { day: "11/20", nameDay: "Anatola, Sedzimira, Rafala" },
  { day: "11/21", nameDay: "Alberta, Janusza, Konrada" },
  { day: "11/22", nameDay: "Cecylii, Wszemily, Stefana" },
  { day: "11/23", nameDay: "Adelii, Klemensa, Felicyty" },
  { day: "11/24", nameDay: "Flory, Emmy, Chryzogona" },
  { day: "11/25", nameDay: "Erazma, Katarzyny" },
  { day: "11/26", nameDay: "Delfiny, Sylwestra, Konrada" },
  { day: "11/27", nameDay: "Waleriana, Wirgiliusza, Maksyma" },
  { day: "11/28", nameDay: "Leslawa, Zdzislawa, Stefana" },
  { day: "11/29", nameDay: "Blazeja, Saturnina" },
  { day: "11/30", nameDay: "Andrzeja, Maury, Konstantego" },
  { day: "12/01", nameDay: "Natalii, Eligiusza, Edmunda" },
  { day: "12/02", nameDay: "Balbiny, Bibianny, Pauliny" },
  { day: "12/03", nameDay: "Franciszka, Ksawerego, Kasjana" },
  { day: "12/04", nameDay: "Barbary, Krystiana, Jana" },
  { day: "12/05", nameDay: "Sabiny, Krystyny, Edyty" },
  { day: "12/06", nameDay: "Mikołaja, Jaremy, Emiliana" },
  { day: "12/07", nameDay: "Marcina, Ambrożego, Teodora" },
  { day: "12/08", nameDay: "Marii, Światozara, Makarego" },
  { day: "12/09", nameDay: "Wiesława Leokadii Joanny" },
  { day: "12/10", nameDay: "Julii, Danieli, Bogdana" },
  { day: "12/11", nameDay: "Damazego, Waldemara, Daniela" },
  { day: "12/12", nameDay: "Dagmary, Aleksandra, Ady" },
  { day: "12/13", nameDay: "Lucji, Otylii" },
  { day: "12/14", nameDay: "Alfreda, Izydora, Jana" },
  { day: "12/15", nameDay: "Niny, Celiny, Waleriana" },
  { day: "12/16", nameDay: "Albiny, Zdzisławy, Alicji" },
  { day: "12/17", nameDay: "Olimpii, Lazarza, Floriana" },
  { day: "12/18", nameDay: "Gracjana, Bogusława, Laurencji" },
  { day: "12/19", nameDay: "Gabrieli, Dariusza, Eleonory" },
  { day: "12/20", nameDay: "Bogumi³y, Dominika" },
  { day: "12/21", nameDay: "Tomis³awa, Seweryna, Piotra" },
  { day: "12/22", nameDay: "Zenona, Honoraty, Franciszki" },
  { day: "12/23", nameDay: "Wiktorii, Sławomiry, Jana" },
  { day: "12/24", nameDay: "Adama, Ewy, Eweliny" },
  { day: "12/25", nameDay: "Anastazji, Eugenii" },
  { day: "12/26", nameDay: "Dionizego, Szczepana" },
  { day: "12/27", nameDay: "Jana, ¯anety, Maksyma" },
  { day: "12/28", nameDay: "Teofilii, Godzisława, Cezarego" },
  { day: "12/29", nameDay: "Dawida, Tomasza, Dominika" },
  { day: "12/30", nameDay: "Rainera, Eugeniusza, Irmy" },
  { day: "12/31", nameDay: "Sylwestra, Melanii, Mariusza" },
];

const NameDay = names.filter(({ day }) => currentDate === day)
            .map(({ nameDay }) => (
              {nameDay}
            ));
const ShowName = NameDay.map((item) => {
  return item.nameDay;
});

document.getElementById("nameDay").innerHTML = ShowName;


//Weather

const token = config.SECRET_API_KEY;
const City = "Lidzbark Warmiński";
const apiKey = token;
const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${City}&lang=pl&appid=${apiKey}`;



fetch(apiUrl)
  .then((res) => res.json())
  .then((res) => {
    const ResName = res.name; 
    const Icon = res.weather[0].icon; 
    const Description = res.weather[0].description;    
    const Temp = Math.round(res.main.temp - 273.15)
         .toFixed(1)
         .toString();
    const Feels_like = (res.main.feels_like - 273.15)
         .toFixed(1)
         .toString();   
     const Speed = res.wind.speed;
     const Humidity = res.main.humidity;
     const Pressure = res.main.pressure; 
      const ImgSrc = `http://openweathermap.org/img/wn/${Icon}@4x.png`;

document.getElementById("ResName").innerHTML = ResName;
document.getElementById("Description").innerHTML = Description;
document.getElementById("Temp").innerHTML = Temp;
document.getElementById("Feels_like").innerHTML = Feels_like;
document.getElementById("Speed").innerHTML = Speed;
document.getElementById("Pressure").innerHTML = Pressure;
document.getElementById("Humidity").innerHTML = Humidity;   

const image = document.createElement("img");
image.setAttribute("src", ImgSrc);
image.setAttribute("alt", "Ikonka pogody");
document.getElementById("Image").appendChild(image);


  })
  .catch((error) => console.log("Błąd: ", error));


